name: 'print-devices'

on:
  schedule:
    - cron: '13 4,16 * * *'

jobs:
  print:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os:
          - macos-12
          - macos-13
          - macos-14
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: Wiki
          token: ${{ secrets.FASTLANE_UPDATE_GITHUB_TOKEN }}
      - run: >
          grep '${{ matrix.os }}' Home.md ||
          echo '- [`${{ matrix.os }}`](Devices-${{ matrix.os }})' >>
          Home.md
        working-directory: Wiki
      - run: npm run print-devices -- Wiki/Devices-${{ matrix.os }}.md
      - run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m 'Update the list of devices'
            git push
          fi
        working-directory: Wiki
